apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-frontend-deployment
  namespace: default
  labels:
    app: casino-frontend
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: casino-frontend
  template:
    metadata:
      labels:
        app: casino-frontend
    spec:
      containers:
      - name: casino-frontend
        image: casino-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"