apiVersion: v1
kind: Service
metadata:
  name: casino-frontend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: casino-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080